
export const INPUT_CHANGE = "INPUT_CHANGE";
export const GET_STARSHIP_SUCCESS = "GET_STARSHIP_SUCCESS";
export const GET_STARSHIP_FAILURE = "GET_STARSHIP_FAILURE";
export const UPDATE_STARSHIP_COUNT_SUCCESS = "UPDATE_STARSHIP_COUNT_SUCCESS";
export const UPDATE_STARSHIP_COUNT_FAILURE = "UPDATE_STARSHIP_COUNT_FAILURE";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const GET_ERRORS = "GET_ERRORS";
